name: "Main Workflow"

#trigger
on:
  pull_request:
    branches:
      - dev

jobs: 
  build:
    name: "Build laravel App"
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: |
          composer install

      - name: Build the application
        run: |
          php artisan key:generate